update dependencies.
dkdeploy/dkdeploy-php pull request #10
Opened 2017-10-16 08:07 UTC by Medesis

2017-10-16 08:46 UTC, ncreuschling requested changes

2017-10-16 08:46 UTC, ncreuschling commented on .travis.yml
> +  - 2.3.4
We should add Ruby `2.2` here as well. Use `2.3` and `2.4`. (See `dkdeploy-core`)

2017-10-16 08:46 UTC, ncreuschling commented on dkdeploy-php.gemspec
> +  spec.add_development_dependency 'rubocop', '~> 0.50'
Make it consistent with dkdeploy-core: `~> 0.50.0`

2017-10-16 08:46 UTC, ncreuschling commented on lib/dkdeploy/php/tasks/composer.rake
> +      rescue ComposerError
Where does this exception class come from?

2017-10-16 08:51 UTC, ncreuschling requested changes

2017-10-16 08:51 UTC, ncreuschling commented on .travis.yml
> +  - bundle exec rubocop --display-cop-names --extra-details
Please import these settings into `.rubocop.yml`. (See `dkdeploy-core`)

2017-10-16 08:52 UTC, websi requested changes

2017-10-16 08:52 UTC, websi commented on .travis.yml
> +  - 2.3.4
Please use `2.2`, `2.3` and `2.4`. 

See https://github.com/dkdeploy/dkdeploy-core/commit/82ff875a1821aa2e189d25bfeac0c9def6534b60#diff-354f30a63fb0907d4ad57269548329e3

2017-10-16 08:52 UTC, websi commented on CHANGELOG.md
> +
Please remove empty lines

2017-10-16 08:52 UTC, websi commented on dkdeploy-php.gemspec
> +  spec.add_development_dependency 'rubocop', '~> 0.50'
Please use `'~> 0.50.0'`

2017-10-16 08:52 UTC, websi commented on lib/dkdeploy/php/tasks/composer.rake
> +      rescue ComposerError
Please use `SSHKit::StandardError`

2017-10-16 08:52 UTC, websi commented on spec/fixtures/application/config/deploy/dev.rb
> +server 'dkdeploy-php.dev', roles: %w[web app backend], primary: true
`web`, `app` and `backend` are strings or symbols.

2017-10-16 08:52 UTC, websi commented on spec/fixtures/application/config/deploy/dev.rb
> +set :copy_exclude, %w[
The content of the array are `strings`. No variables or methods.

2017-10-16 08:52 UTC, websi commented on spec/fixtures/capistrano/configuration/server_with_faulty_domain_configuration.rb
> +server 'dkdeploy-php.dev', roles: %w[web app backend], domain: 'not-existing-dkdeploy.dev'
The content of the array are `strings`. No variables or methods.

2017-10-16 08:52 UTC, websi commented on spec/fixtures/capistrano/configuration/server_with_ssl.rb
> +server 'dkdeploy-php.dev', roles: %w[web app backend], primary: true, domain_scheme: 'https'
The content of the array are `strings`. No variables or methods.

2017-10-16 08:52 UTC, websi commented on spec/fixtures/capistrano/configuration/server_with_valid_domain.rb
> +server 'dkdeploy-php.dev', roles: %w[web app backend], domain: 'second-dkdeploy-php.dev'
The content of the array are `strings`. No variables or methods.

2017-10-16 08:53 UTC, websi commented on spec/fixtures/application/config/deploy/dev.rb
> +server 'dkdeploy-php.dev', roles: %w[web app backend], primary: true
My fault. No changes required.

2017-10-16 08:53 UTC, websi commented on spec/fixtures/application/config/deploy/dev.rb
> +set :copy_exclude, %w[
My fault. No changes required.

2017-10-16 08:53 UTC, websi commented on spec/fixtures/capistrano/configuration/server_with_faulty_domain_configuration.rb
> +server 'dkdeploy-php.dev', roles: %w[web app backend], domain: 'not-existing-dkdeploy.dev'
My fault. No changes required.

2017-10-16 08:54 UTC, websi commented on spec/fixtures/capistrano/configuration/server_with_ssl.rb
> +server 'dkdeploy-php.dev', roles: %w[web app backend], primary: true, domain_scheme: 'https'
My fault. No changes required.

2017-10-16 08:54 UTC, websi commented on spec/fixtures/capistrano/configuration/server_with_valid_domain.rb
> +server 'dkdeploy-php.dev', roles: %w[web app backend], domain: 'second-dkdeploy-php.dev'
My fault. No changes required.

2017-10-16 12:28 UTC, ncreuschling commented on .rubocop.yml
> +  Enabled: false
We should use the same options as in `dkdeploy-core`:

```
  TargetRubyVersion: 2.2
  ExtraDetails: true
  DisplayStyleGuide: true
  DisplayCopNames: true
```

2017-10-16 12:31 UTC, ncreuschling requested changes

2017-10-16 12:31 UTC, ncreuschling commented on .rubocop.yml
> +  Enabled: false
We should use the same options as in `dkdeploy-core`:

```
  TargetRubyVersion: 2.2
  ExtraDetails: true
  DisplayStyleGuide: true
  DisplayCopNames: true
```

2017-10-16 12:38 UTC, ncreuschling approved these changes

2017-10-16 12:39 UTC, ncreuschling commented
Looks ok to me.

2017-10-16 13:11 UTC, websi requested changes
Please Update Vagrant. 
Please update gemspec

See https://github.com/dkdeploy/dkdeploy-core/compare/v8.0.0...v9.0.0

2017-10-16 14:12 UTC, websi submitted a review, later dismissed

2017-10-16 14:38 UTC, websi requested changes
Please check travis build

2017-10-17 07:10 UTC, websi approved these changes

2017-10-17 07:10 UTC, merged