Enable SSL certificate check in http helper
dkdeploy/dkdeploy-php pull request #5
Opened 2016-10-18 12:04 UTC by klyonrad

# Summary

This removes bypassing the SSL certificate check in the custom http helper.

# Test Plan

- `vagrant provision`
- `cucumber`

2016-10-18 12:05 UTC, klyonrad commented on lib/dkdeploy/php/helpers/http.rb
> +            http.verify_mode = OpenSSL::SSL::VERIFY_PEER
`VERIFY_PEER` is the default and this line could actually be removed. But this way the change is more explicit

2016-10-18 12:09 UTC, ncreuschling requested changes

2016-10-18 12:09 UTC, ncreuschling commented on config/vm/cookbooks/dkdeploy-php/recipes/default.rb
> +  email 'luka.luedicke@dkd.de'
Please remove personal reference. Replace with example.com address.

2016-10-18 12:09 UTC, ncreuschling commented on config/vm/cookbooks/dkdeploy-php/recipes/default.rb
> +my_key_path = '/var/www/dkdeploy.key'
Make customizable or move inline.

2016-10-18 12:09 UTC, ncreuschling commented on config/vm/cookbooks/dkdeploy-php/recipes/default.rb
> +  email 'luka.luedicke@dkd.de'
Dito

2016-10-18 12:09 UTC, ncreuschling commented on config/vm/cookbooks/dkdeploy-php/templates/default/web_app.conf.erb
> +    SSLCertificateFile /var/www/dkdeploy.pem
Use variable from recipe.

2016-10-18 12:19 UTC, websi requested changes

2016-10-18 12:19 UTC, websi commented on config/vm/cookbooks/dkdeploy-php/metadata.rb
> +depends 'ssl_certificate'
Please add version number for `ssl_certificate`

2016-10-18 12:19 UTC, websi commented on features/php.feature
> +		Given I set relative to current path the environment variable "SSL_CERT_FILE" to "/tmp/aruba/temp/dkdeploy.dkdeploy-php.dev.pem"
Why `relative to current`?
Can you remove path `/tmp/aruba/temp/`?

2016-10-18 12:19 UTC, websi commented on features/php.feature
> +		When I run `cap dev utils:download_file[../../../dkdeploy.pem]`
Is this necessary?

2016-10-18 12:19 UTC, websi commented on lib/dkdeploy/php/helpers/http.rb
> +            http.verify_mode = OpenSSL::SSL::VERIFY_PEER
Maybe implement an configuration option for this.

2016-10-18 13:36 UTC, klyonrad commented on features/php.feature
> +		Given I set relative to current path the environment variable "SSL_CERT_FILE" to "/tmp/aruba/temp/dkdeploy.dkdeploy-php.dev.pem"
We need the absolute path to the certificate file and string interpolation is possible in the cucumber step.  The RegExp match data alwasy escapes the special charachter for string interpolation

2016-10-18 13:43 UTC, klyonrad commented on features/php.feature
> +		Given I set relative to current path the environment variable "SSL_CERT_FILE" to "/tmp/aruba/temp/dkdeploy.dkdeploy-php.dev.pem"
> Can you remove path /tmp/aruba/temp/?

Yeah, I am using the `test_app_path` method now in the step definition

2016-10-18 13:44 UTC, klyonrad commented on features/php.feature
> +		When I run `cap dev utils:download_file[../../../dkdeploy.pem]`
The certificate needs to get copied from the test VM in some way

2016-10-18 15:05 UTC, klyonrad commented on lib/dkdeploy/php/helpers/http.rb
> +            http.verify_mode = OpenSSL::SSL::VERIFY_NONE if disable_ssl_check
@websi I guess you would like that configurable in the server properties and how should it be called?

2016-11-04 12:23 UTC, klyonrad commented
made some improvements, updated changelog

2016-11-22 14:41 UTC, websi commented on lib/dkdeploy/php/helpers/http.rb
> +          http_get_with_redirect url: url, verify_mode: ssl_verify_mode
Is this a breaking change?
If yes, we need to document this breaking change.
Or can we use `http_get_with_redirect(url, limit = 5, verify_mode: OpenSSL::SSL::VERIFY_PEER)`?

2016-11-22 14:42 UTC, websi commented on lib/dkdeploy/php/helpers/http.rb
> +        def http_get_with_redirect(url:, limit: 5, verify_mode: OpenSSL::SSL::VERIFY_PEER)
Is this a breaking change?
If yes, we need to document this breaking change.
Or can we use http_get_with_redirect(url, limit = 5, verify_mode: OpenSSL::SSL::VERIFY_PEER)?

2016-11-22 14:43 UTC, klyonrad commented on lib/dkdeploy/php/helpers/http.rb
> +        def http_get_with_redirect(url:, limit: 5, verify_mode: OpenSSL::SSL::VERIFY_PEER)
Uhm yes, breaking, I documented that in the changelog in the section _Changed_

2017-04-07 10:24 UTC, websi submitted a review, later dismissed

2017-04-07 10:24 UTC, websi commented on config/vm/cookbooks/dkdeploy-php/recipes/default.rb
> +  email 'offical@example.com'
Please use no example email address.

2017-04-07 11:46 UTC, websi approved these changes
@ncreuschling can you take a look of this

2017-04-10 07:21 UTC, ncreuschling commented on .rubocop.yml
> +  TargetRubyVersion: 2.1
We will target v2.2 now.

2017-04-10 07:24 UTC, ncreuschling approved these changes

2017-04-10 07:25 UTC, ncreuschling commented
Please squash and rebase. Then we'll merge it.

2017-04-10 08:17 UTC, merged